on: [push]

jobs:
  security_checks:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    name: Execute the Duo Dlint action against setup.py
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run Dlint from Duo
      run: |
        python -m pip install --upgrade pip
        cd ./Python
        test -f ./setup.py && python3 setup.py install
        pip3 freeze > requirements.txt
        pip3 install dlint
        python3 -m flake8 --select=DUO ./Python
