name: 'PyCharm Security'

on:
  push:
  pull_request:
  schedule:
    - cron: '* * 3 * *'

jobs:
  security_checks:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    name: Execute the pycharm-security action
    steps:
      - uses: actions/checkout@v4    
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Run PyCharm Security
        uses: tonybaloney/pycharm-security@master
        with:
          path: Python/
